export const ADMIN_ACTORS_REQUEST = 'ADMIN_ACTORS_REQUEST';
export const ADMIN_ACTORS_SUCCESS = 'ADMIN_ACTORS_SUCCESS';
export const ADMIN_ACTORS_FAIL = 'ADMIN_ACTORS_FAIL';

export const ALL_ACTORS_REQUEST = 'ALL_ACTORS_REQUEST';
export const ALL_ACTORS_SUCCESS = 'ALL_ACTORS_SUCCESS';
export const ALL_ACTORS_FAIL = 'ALL_ACTORS_FAIL';

export const NEW_ACTOR_REQUEST = 'NEW_ACTOR_REQUEST'
export const NEW_ACTOR_SUCCESS = 'NEW_ACTOR_SUCCESS'
export const NEW_ACTOR_RESET = 'NEW_ACTOR_RESET'
export const NEW_ACTOR_FAIL = 'NEW_ACTOR_FAIL'

export const DELETE_ACTOR_REQUEST = 'DELETE_ACTOR_REQUEST'
export const DELETE_ACTOR_SUCCESS = 'DELETE_ACTOR_SUCCESS'
export const DELETE_ACTOR_RESET = 'DELETE_ACTOR_RESET'
export const DELETE_ACTOR_FAIL = 'DELETE_ACTOR_FAIL'

export const UPDATE_ACTOR_REQUEST = 'UPDATE_ACTOR_REQUEST'
export const UPDATE_ACTOR_SUCCESS = 'UPDATE_ACTOR_SUCCESS'
export const UPDATE_ACTOR_RESET = 'UPDATE_ACTOR_RESET'
export const UPDATE_ACTOR_FAIL = 'UPDATE_ACTOR_FAIL'

export const ACTOR_DETAILS_REQUEST = 'ACTOR_DETAILS_REQUEST';
export const ACTOR_DETAILS_SUCCESS = 'ACTOR_DETAILS_SUCCESS';
export const ACTOR_DETAILS_FAIL = 'ACTOR_DETAILS_FAIL';

export const NEW_ACTOR_REVIEW_REQUEST = 'NEW_ACTOR_REVIEW_REQUEST'
export const NEW_ACTOR_REVIEW_SUCCESS = 'NEW_ACTOR_REVIEW_SUCCESS'
export const NEW_ACTOR_REVIEW_RESET = 'NEW_ACTOR_REVIEW_RESET'
export const NEW_ACTOR_REVIEW_FAIL = 'NEW_ACTOR_REVIEW_FAIL'

export const GET_ACTOR_REVIEWS_REQUEST = 'GET_ACTOR_REVIEWS_REQUEST'
export const GET_ACTOR_REVIEWS_SUCCESS = 'GET_ACTOR_REVIEWS_SUCCESS'
export const GET_ACTOR_REVIEWS_FAIL = 'GET_ACTOR_REVIEWS_FAIL'

export const DELETE_ACTOR_REVIEW_REQUEST = 'DELETE_ACTOR_REVIEW_REQUEST'
export const DELETE_ACTOR_REVIEW_SUCCESS = 'DELETE_ACTOR_REVIEW_SUCCESS'
export const DELETE_ACTOR_REVIEW_RESET = 'DELETE_ACTOR_REVIEW_RESET'
export const DELETE_ACTOR_REVIEW_FAIL = 'DELETE_ACTOR_REVIEW_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
