export const ADMIN_PRODUCERS_REQUEST = 'ADMIN_PRODUCERS_REQUEST';
export const ADMIN_PRODUCERS_SUCCESS = 'ADMIN_PRODUCERS_SUCCESS';
export const ADMIN_PRODUCERS_FAIL = 'ADMIN_PRODUCERS_FAIL';

export const ALL_PRODUCERS_REQUEST = 'ALL_PRODUCERS_REQUEST';
export const ALL_PRODUCERS_SUCCESS = 'ALL_PRODUCERS_SUCCESS';
export const ALL_PRODUCERS_FAIL = 'ALL_PRODUCERS_FAIL';

export const NEW_PRODUCER_REQUEST = 'NEW_PRODUCER_REQUEST';
export const NEW_PRODUCER_SUCCESS = 'NEW_PRODUCER_SUCCESS';
export const NEW_PRODUCER_RESET = 'NEW_PRODUCER_RESET';
export const NEW_PRODUCER_FAIL = 'NEW_PRODUCER_FAIL';

export const DELETE_PRODUCER_REQUEST = 'DELETE_PRODUCER_REQUEST';
export const DELETE_PRODUCER_SUCCESS = 'DELETE_PRODUCER_SUCCESS';
export const DELETE_PRODUCER_RESET = 'DELETE_PRODUCER_RESET';
export const DELETE_PRODUCER_FAIL = 'DELETE_PRODUCER_FAIL';

export const UPDATE_PRODUCER_REQUEST = 'UPDATE_PRODUCER_REQUEST';
export const UPDATE_PRODUCER_SUCCESS = 'UPDATE_PRODUCER_SUCCESS';
export const UPDATE_PRODUCER_RESET = 'UPDATE_PRODUCER_RESET';
export const UPDATE_PRODUCER_FAIL = 'UPDATE_PRODUCER_FAIL';

export const PRODUCER_DETAILS_REQUEST = 'PRODUCER_DETAILS_REQUEST';
export const PRODUCER_DETAILS_SUCCESS = 'PRODUCER_DETAILS_SUCCESS';
export const PRODUCER_DETAILS_FAIL = 'PRODUCER_DETAILS_FAIL';

export const NEW_PRODUCER_REVIEW_REQUEST = 'NEW_PRODUCER_REVIEW_REQUEST';
export const NEW_PRODUCER_REVIEW_SUCCESS = 'NEW_PRODUCER_REVIEW_SUCCESS';
export const NEW_PRODUCER_REVIEW_RESET = 'NEW_PRODUCER_REVIEW_RESET';
export const NEW_PRODUCER_REVIEW_FAIL = 'NEW_PRODUCER_REVIEW_FAIL';

export const GET_PRODUCER_REVIEWS_REQUEST = 'GET_PRODUCER_REVIEWS_REQUEST';
export const GET_PRODUCER_REVIEWS_SUCCESS = 'GET_PRODUCER_REVIEWS_SUCCESS';
export const GET_PRODUCER_REVIEWS_FAIL = 'GET_PRODUCER_REVIEWS_FAIL';

export const DELETE_PRODUCER_REVIEW_REQUEST = 'DELETE_PRODUCER_REVIEW_REQUEST';
export const DELETE_PRODUCER_REVIEW_SUCCESS = 'DELETE_PRODUCER_REVIEW_SUCCESS';
export const DELETE_PRODUCER_REVIEW_RESET = 'DELETE_PRODUCER_REVIEW_RESET';
export const DELETE_PRODUCER_REVIEW_FAIL = 'DELETE_PRODUCER_REVIEW_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
